development:
  adapter: postgresql
  encoding: unicode
  database: grupo_development
  pool: 5
  username: <%= ENV['RAILS_DB_USER'] %>
  password: <%= ENV['RAILS_DB_PWD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: grupo_test
  pool: 5
  username: <%= ENV['RAILS_DB_USER'] %>
  password: <%= ENV['RAILS_DB_PWD'] %>
