development:
  adapter: postgresql
  encoding: unicode
  database: grupo_development
  pool: 5
  username: pguser
  password: pguser

test:
  adapter: postgresql
  encoding: unicode
  database: grupo_test
  pool: 5
  username: pguser
  password: pguser
