development:
  adapter: postgresql
  encoding: unicode
  database: grupo_development
  pool: 5
  username: mariajose
  password: majose

test:
  adapter: postgresql
  encoding: unicode
  database: grupo_test
  pool: 5
  username: mariajose
  password: majose
